### ISSUE TITLE
/opt/zabbix/gluster/heal.sh returning empty value

### ISSUE THREAD

**Issue by digidax** [burner1024/zabbix-gluster#2]
1st Issue
[root@cluster-stor1 gluster]# sh heal.sh ' ' 0
=> no value returned, so Trigger detects a pending healing but there isn't:

[root@cluster-stor1 gluster]# gluster volume heal volume1 info
Brick 192.168.110.221:/bricks/raid5array1/brick1
Status: Connected
Number of entries: 0

Brick 192.168.110.222:/bricks/raid5array1/brick1
Status: Connected
Number of entries: 0

Brick 192.168.110.223:/bricks/raid5array1/brick1
Status: Connected
Number of entries: 0

------------------------------------------------------------------------------------------

2nd Issue
[root@cluster-stor1 gluster]# sh heal.sh split-brain 0
=> no value returned, so Trigger detects split brain

--------------------------------------------------------------------------------------------

Sysinfo:
[root@cluster-stor1 gluster]# gluster volume list
volume1

[root@cluster-stor1 gluster]# uname -a
Linux cluster-stor1.cbr1.de 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

CentOS release 6.6 (Final)

[root@cluster-stor1 gluster]# glusterd -V
glusterfs 3.12.1

**Comment by burner1024** [comment]
Sorry, I don't have a Gluster installation at this moment, so can't check. You're welcome to send a pull.

**Comment by linecolumn** [comment]
Confirmed. This script is not working, and is spewing split-brain and heal-pending as result.

**Comment by linecolumn** [comment]
It seems that you need to comment out

set -eu -o pipefail

as it is suppressing output(s) of the script.

**Comment by burner1024** [comment]
It must not be commented out. Try running with -x, see which command fails and why.

**Comment by burner1024** [comment]
probably related to #4
