### ISSUE TITLE
getting -1 as value

### ISSUE THREAD

**Issue by digidax** [burner1024/zabbix-gluster#6]
I getting -1 as value back from some servers for the offline bricks and the self heal status.

Looking to the collection script:

`if item=$(timeout -s 9 1 sudo gluster volume status 2>/dev/null | grep rick1 | awk '{print $4}'); then echo "$item" | grep -c N; else echo '-1'; fi`

-1 will be displayed after a timeout - right?

Have running the command line above parallel in a loop on the same machine. The output of the loop was within one hour everytime 0, but the agent sends over 6 times within this hour a -1

Any ideas?

Have now set the timeout from 1 to 2 seconds: `... timeout -s 9 2 sudo ...`

**Comment by burner1024** [comment]
> -1 will be displayed after a timeout - right?

right
